version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:3.4
    command: --nojournal
  orion:
    image: fiware/orion-ld
    links:
      - mongo
    ports:
      - "1026:1026"
    environment:
      - ORIONLD_MONGO_HOST=mongo
      - ORIONLD_DISABLE_FILE_LOG=TRUE
      - ORIONLD_MULTI_SERVICE=TRUE
      

